ERM-999: Add record/row identifiers into Local KB Admin log display
folio-org/stripes-erm-components pull request #283
Opened 2020-09-18 13:32 UTC by peterboehm

2020-09-18 15:45 UTC, aditya-matukumalli commented on lib/LogsList/LogsList.js
> +        recordDescriptor: ({ additionalInfo }) => {
``
```suggestion
        recordDescriptor: ({ additionalInfo = {} }) => {
```

2020-09-18 15:56 UTC, aditya-matukumalli requested changes
Looks good to me. Some minor tweaks and linitng errors need to be fixed.

2020-09-18 15:56 UTC, aditya-matukumalli commented on lib/LogsList/LogsList.js
> +        recordDescriptor: ({ additionalInfo }) => {
```suggestion
        recordDescriptor: ({ additionalInfo = {} }) => {
          const { packageSource, packageSource, rowNumber, recordNumber } = additionalInfo;
```

2020-09-18 15:56 UTC, aditya-matukumalli commented on lib/LogsList/LogsList.js
> +                </div>
With the above requested change the `additionalInfo.packageSource ` could just be replaced with `packageSource`. Similarly with  `packageReference`, `rowNumber` and `recordNumber`. Its more cleaner that way as we dont need to fetch the property from `additionalInfo` everytime.

2020-09-18 15:56 UTC, aditya-matukumalli commented on translations/stripes-erm-components/en.json
> +  "columns.recordDescriptor": "Record descriptor",
Its best to leave an empty line between lines 18 and 19 just to differentiate the related translations

2020-09-18 15:56 UTC, aditya-matukumalli commented on translations/stripes-erm-components/en_US.json
> +    "recordNumber": "Record number: {recordnumber}",
Only translations that are already present have to be edited in the `en_US.json` file. New translations `shouldn't` be added here and adding them only to `en.json` should suffice.

2020-09-21 15:59 UTC, peterboehm commented
@aditya-matukumalli Thanks for the suggestions! I updated the code accordingly

2020-09-21 20:46 UTC, aditya-matukumalli approved these changes

2020-09-21 20:50 UTC, merged